# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-26 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=42)),
                ('street_address_1', models.CharField(max_length=32)),
                ('street_address_2', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=24)),
                ('postcode', models.CharField(max_length=12)),
                ('county', models.CharField(max_length=24)),
                ('country', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
