# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-31 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='BillingAddress',
        ),
    ]
