# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-24 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='street_address_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='street_address_2',
        ),
    ]
