# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-17 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('LABONE', 'Label One'), ('LABTWO', 'Label Two'), ('LABTHR', 'Label Three'), ('LABFOU', 'Label Four'), ('LABFIV', 'Label Five'), ('LABSIX', 'Label Six'), ('LABSEV', 'Label Seven')], default='LABONE', max_length=6)),
                ('product_category', models.CharField(choices=[('Upper-body', (('JACPAR', 'Parka'), ('JACCOA', 'Coat'), ('JACJAC', 'Jacket'), ('SWESWE', 'Sweatshirt'), ('SWEHOO', 'Hoodie'), ('SHILON', 'Long Sleeve Shirt'), ('SHISHO', 'Short Sleeve Shirt'), ('TSHLON', 'Long Sleeve T-Shirt'), ('TSHSHO', 'Short Sleeve T-Shirt'), ('TSHPOL', 'Polo Shirt'))), ('Lower-body', (('PANJEA', 'Jeans'), ('PANCAR', 'Cargo'), ('PANCHI', 'Chino'), ('PANSHO', 'Shorts'), ('DREDRE', 'Dress'), ('DRESKI', 'Skirt'))), ('Accesories', (('ACCBEA', 'Beanie'), ('ACCCAP', 'Cap'), ('ACCBAG', 'Bag'), ('ACCBEL', 'Belt'), ('ACCWAL', 'Wallet'), ('ACCSUN', 'Sunglasses'), ('ACCSWI', 'Swimsuit'), ('ACCJEW', 'Jewelry')))], default='JACPAR', max_length=6)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('NA', 'Not Applicable'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='NA', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
                ('quantity', models.IntegerField(default=1)),
                ('person_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.MainFilter')),
            ],
        ),
    ]
