# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200417_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='person_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.GenderFilter'),
        ),
        migrations.DeleteModel(
            name='MainFilter',
        ),
    ]
