# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200407_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Men', (('MJACPAR', 'Parka'), ('MJACCOA', 'Coat'), ('MJACJAC', 'Jacket'), ('MSWESWE', 'Sweatshirt'), ('MSWEHOO', 'Hoodie'), ('MSHILON', 'Long Sleeve Shirt'), ('MSHISHO', 'Short Sleeve Shirt'), ('MTSHLON', 'Long Sleeve T-Shirt'), ('MTSHSHO', 'Short Sleeve T-Shirt'), ('MTSHPOL', 'Polo Shirt'), ('MPANJEA', 'Jeans'), ('MPANCAR', 'Cargo'), ('MPANCHI', 'Chino'), ('MPANSHO', 'Shorts'), ('MACCBEA', 'Beanie'), ('MACCCAP', 'Cap'), ('MACCBAG', 'Bag'), ('MACCBEL', 'Belt'), ('MACCWAL', 'Wallet'), ('MACCSUN', 'Sunglasses'))), ('Women', (('WJACCOA', 'Coat'), ('WJACJAC', 'Jacket'), ('WSWESWE', 'Sweatshirt'), ('WSWEHOO', 'Hoodie'), ('WSHILON', 'Long Sleeve Shirt'), ('WSHISHO', 'Short Sleeve Shirt'), ('WTSHLON', 'Long SLeeve T-Shirt'), ('WTSHSHO', 'Short Sleeve T-Shirt'), ('WDREDRE', 'Dress'), ('WDRESKI', 'Skirt'), ('WPANJEA', 'Jeans'), ('WPANCAR', 'Cargo'), ('WPANSHO', 'Shorts'), ('WACCBAG', 'Bag'), ('WACCSWI', 'Swimsuit'), ('WACCJEW', 'Jewelry'))), ('Kids', (('KJACJAC', 'Jacket'), ('KSEWSWE', 'Sweatshirt'), ('KSWEHOO', 'Hoodie'), ('KSHILON', 'Long Sleeve Shirt'), ('KSHISHO', 'Short Sleeve Shirt'), ('KTSHLON', 'Long SLeeve T-Shirt'), ('KTSHSHO', 'Short Sleeve T-Shirt'), ('KPANJEA', 'Jeans'), ('KPANSHO', 'Shorts')))], default='MJACPAR', max_length=7),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='XS', max_length=3),
        ),
    ]
