# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-13 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200413_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfilter',
            name='person_category',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='person_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.MainFilter'),
        ),
    ]
