# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-13 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200413_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainfilter',
            old_name='pers_category',
            new_name='person_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='person_category',
        ),
        migrations.AddField(
            model_name='product',
            name='person_category',
            field=models.ManyToManyField(to='products.MainFilter'),
        ),
    ]
