# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200413_1711'),
    ]

    operations = [
        
    ]
