# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-13 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200413_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfilter',
            name='category',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids')], max_length=1, null=True),
        ),
    ]
