# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-13 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200413_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='person_category',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids')], default='M', max_length=1),
        ),
        migrations.DeleteModel(
            name='MainFilter',
        ),
    ]
