# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-14 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20200413_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='person_category',
            field=models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('K', 'Kids')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Upper-body', (('JACPAR', 'Parka'), ('JACCOA', 'Coat'), ('JACJAC', 'Jacket'), ('SWESWE', 'Sweatshirt'), ('SWEHOO', 'Hoodie'), ('SHILON', 'Long Sleeve Shirt'), ('SHISHO', 'Short Sleeve Shirt'), ('TSHLON', 'Long Sleeve T-Shirt'), ('TSHSHO', 'Short Sleeve T-Shirt'), ('TSHPOL', 'Polo Shirt'))), ('Lower-body', (('PANJEA', 'Jeans'), ('PANCAR', 'Cargo'), ('PANCHI', 'Chino'), ('PANSHO', 'Shorts'), ('DREDRE', 'Dress'), ('DRESKI', 'Skirt'))), ('Accesories', (('ACCBEA', 'Beanie'), ('ACCCAP', 'Cap'), ('ACCBAG', 'Bag'), ('ACCBEL', 'Belt'), ('ACCWAL', 'Wallet'), ('ACCSUN', 'Sunglasses'), ('ACCSWI', 'Swimsuit'), ('ACCJEW', 'Jewelry')))], default='JACPAR', max_length=6),
        ),
    ]
